#!/usr/bin/env bash

# Description:
#     Processes the data using an awk script called preprocess.awk and outputs the result to standard output.
#     Adds month and year columns to the data, shorten the type of breach, and remove the unnecessary columns.

# Author: Nicholas Choong 21980614

# Check for the right number of arguments
if [[ $# -ne 1 ]]; then
  echo "Error: Incorrect number of arguments." >/dev/stderr
  echo "Usage: $0 <file name>" >/dev/stderr
  exit 0
fi

file="$1"

# Check if the output file exists
if [[ ! -s "${file}" ]] || [[ "${file##*.}" != "tsv" ]]; then
  echo "File ${file} must be a non-zero length .tsv file" >/dev/stderr
  exit 1
fi

# Process the data
awk -f preprocess.awk "${file}"

exit 0
